//
//  GSAssignmentStatus.swift
//  GapStaffEmployee
//
//  Created by Vasant Hugar on 09/01/18.
//  Copyright © 2018 Vasant Indpro. All rights reserved.
//

import Foundation

public enum GSAssignmentStatus: String {
    
    case ASSIGNED = "ASSIGNED"
    
    case CAN_APPLY = "CAN_APPLY"
    
    case CAN_APPLY_DECLINED = "CAN_APPLY_DECLINED"
    
    case APPLIED = "APPLIED"
    
    case APPLIED_BINDING = "APPLIED_BINDING"
    
    case INVITATION_REQUEST = "INVITATION_REQUEST"
    
    case INVITATION_REQUEST_DECLINED = "INVITATION_REQUEST_DECLINED"
    
    case INVITATION_NOTIFICATION = "INVITATION_NOTIFICATION"
    
    case TRANSFER_AWAITING_APPROVAL = "TRANSFER_AWAITING_APPROVAL"
    
    case TRANSFER_APPLIED = "TRANSFER_APPLIED"
    
    case TRANSFER_AVAILABLE = "TRANSFER_AVAILABLE"
    
    case TRANSFER_APPLICATION_DECLINED = "TRANSFER_APPLICATION_DECLINED"
    
    case TRANSFER_APPLICATION_APPLIED_SWAP = "TRANSFER_APPLICATION_APPLIED_SWAP"
    
    case TRANSFER_APPLICATION_APPLIED = "TRANSFER_APPLICATION_APPLIED"
    
    case TRANSFER_APPLIED_SWAP = "TRANSFER_APPLIED_SWAP"
    
    case TRANSFER_APPLICATION_AWAITING_APPROVAL = "TRANSFER_APPLICATION_AWAITING_APPROVAL"
    
    case TRANSFER_GIVE_AWAY_CONFIRMED = "TRANSFER_GIVE_AWAY_CONFIRMED"
    
    case TRANSFER_APPLICATION_AWAITING_APPROVAL_SWAP = "TRANSFER_APPLICATION_AWAITING_APPROVAL_SWAP"
    
    case TRANSFER_AWAITING_APPROVAL_SWAP = "TRANSFER_AWAITING_APPROVAL_SWAP"
    
    case TRANSFER_NOT_AVAILABLE = "TRANSFER_NOT_AVAILABLE"
    
    case REMOVE = "REMOVE"
    
    case CANCELED = "CANCELED"
    
    case DECLINED = "DECLINED"
    
    case DECLINED_BY_EMPLOYER = "DECLINED_BY_EMPLOYER"
    
    case CONFIRMED_BY_EMPLOYEE = "CONFIRMED_BY_EMPLOYEE"
    
    case NONE
}
